### ISSUE TITLE
Module not compatible with version 2 of algolia/algoliasearch-magento-2

### ISSUE THREAD

**Issue by dverkade** [algolia/algoliasearch-inventory-magento-2#5]
If you have installed version 2 of the algolia/algoliasearch-magento-2 module, you won't be able to install thie algoliasearch-inventory-magento-2 module. They are not compatible with each other. 

**What's expected**

- Have the ability to use Magento MSI with the latest version of the Algolissearch module.

**Current result**

- Composer throughs an error when you want to install the algoliaserch-inventory-magento-2 module.

**Comment by rachel-trott** [comment]
We released an update to be compatible with algolia/algoliasearch-magento-2 module version 3.7.0.

**Comment by tarun-algolia** [comment]
This issue is fixed with the newly released **algolia/algoliasearch-magento-2** module version 1.0.2 (https://github.com/algolia/algoliasearch-inventory-magento-2/releases/tag/1.0.2)
